spring.application.name=PokeAPICliente

# Configuraci\u00f3n para enviar emails con Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=miguel.masg.2001@gmail.com
spring.mail.password=gtfa hltm uukt cytr
spring.mail.protocol=smtp

spring.mail.starttls=true
spring.mail.properties.mail.smtp.starttls.enable=true
